// 확정된 튜닝 기본값 — 튜닝 패널의 '코드 기본값으로 확정' 버튼이 이 파일을 덮어쓴다.
// git으로 커밋하면 다른 PC에서도 같은 기본값으로 시작한다. 비어 있으면 config.js 원값 사용.
export const TUNED = {
  "dodgeDist": 2,
  "dodgeWindow": 0.5,
  "dodgeCooldown": 0.5,
  "lightRange": 30,
  "lightHalfWidth": 0.6,
  "snapDeg": 3,
  "darkT1": 2.5,
  "darkT2": 5.5,
  "darkT3": 9,
  "slow1": 0.75,
  "slow2": 0.5,
  "vision0": 3.5,
  "vision1": 2.5,
  "vision2": 1,
  "fogAlpha": 0.9,
  "shPatrolSpeed": 1.5,
  "shChaseSpeed": 3,
  "shDashSpeed": 6,
  "shSightRange": 9,
  "shSightHalfAngle": 45,
  "shDashDelay": 1,
  "shDashSafeDist": 12,
  "shDashCd": 6,
  "shLightKillTime": 2,
  "shAuraPatrolHz": 0.4,
  "shAuraPatrolAlpha": 0.31,
  "shAuraPatrolRange": 0.9,
  "shAuraChaseHz": 1.4,
  "shAuraChaseAlpha": 0.5,
  "shAuraChaseRange": 1.4,
  "preset": "감정사",
  "spawnEnabled": true,
  "showDebug": true
};
